name: deploy-html5-itchio
run-name: ${{ github.actor }} is deploying to itch.io
on: [push]
jobs:
  deploy-itch:
    runs-on: ubuntu-latest
    environment: itch
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: main
      
      - name: Checkout export tools
        uses: actions/checkout@v4
        with: 
          repository: andreashsy/godot-export-tools
          path: export-utils
      
      - name: Setup export tools
      - run: |
          unzip export-utils/Godot_v3.5.3-stable_linux_headless.64.zip
          unzip export-utils/butler-linux-amd64.zip
          mv Godot_v3.5.3-stable_linux_headless.64 /usr/local/bin/godot
          mv butler /usr/local/bin/butler
          rm -f *7z*.so

      - name: Build html5
      - run: |
          mkdir export
          godot --path main --export html5cicd ../export/index.html
          zip -j html5.zip export/*

      - name: Deploy
      - run: |
          butler login
          butler push html5.zip andygame/watermelon-game:html5
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}

