name: deploy-html5-itchio
run-name: ${{ github.actor }} is deploying to itch.io
on: [push]
jobs:
  deploy-itch:
    runs-on: ubuntu-latest
    environment: itch
    steps:
      - uses: actions/checkout@v4
        with:
          path: main
      - uses: actions/checkout@v4
        with: 
          repository: andreashsy/godot-export-tools
          path: export-utils

      - run: unzip export-utils/Godot_v3.5.3-stable_linux_headless.64.zip
      - run: mv Godot_v3.5.3-stable_linux_headless.64 /usr/local/bin/godot

      - run: unzip export-utils/butler-linux-amd64.zip
      - run: mv butler /usr/local/bin/butler
      - run: rm -rf *7z*.so
      
      - run: mkdir export
      - run: godot --path main --export html5cicd ../export/index.html
      - run: zip -j html5.zip export/*

      - run: butler login
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
      - run: butler push html5.zip andygame/watermelon-game:html5
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
