name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt install xorg
      - run: wget -P .. https://github.com/godotengine/godot/releases/download/3.5.3-stable/Godot_v3.5.3-stable_x11.64.zip
      - run: unzip ../Godot_v3.5.3-stable_x11.64.zip -d ..
      - run: mv ../Godot_v3.5.3-stable_x11.64 /usr/local/bin/godot
      - run: ls -l ..
      - run: mkdir ../export
      - run: godot --no-window ../export/index.html
      - run: ls -l ..
      - run: ls -l ../export
