name: learn-github-actions
run-name: ${{ github.actor }} is deploying to itch.io
on: [push]
jobs:
  deploy-itch:
    runs-on: ubuntu-latest
    environment: itch
    steps:
      - uses: actions/checkout@v4
        with:
          path: main
      - uses: actions/checkout@v4
        with: 
          repository: andreashsy/godot-export-tools
          path: export-utils
      - run: ls -l
      - run: ls -l export-utils
      - run: ls -l main

      - run: unzip export-utils/Godot_v3.5.3-stable_linux_headless.64.zip -d export-utils
      - run: mv export-utils/Godot_v3.5.3-stable_linux_headless.64 /usr/local/bin/godot
      - run: godot --help
      
      # - run: mkdir ../export
      # - run: godot --export HTML5 ../export/index.html
      # - run: ls -l ../export
      
      # - run: zip -j ../html5.zip ../export/*
      # - run: ls -l ..

      # - run: wget -O ../butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
      # - run: ls -l ..

      # - run: unzip ../butler.zip -d ..
      # - run: mv ../butler /usr/local/bin/butler

      # - run: butler -V
      # - run: butler login
      #   env:
      #     BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
      # - run: butler push ../html5.zip andygame/watermelon-game:html5
      #   env:
      #     BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
